services:
  chives-watch:
    image: public.ecr.aws/docker/library/node:22.11.0-alpine3.19
    container_name: chives-watch
    restart: always
    ports:
    - '127.0.0.1:3000:3000'
    working_dir: /app
    volumes:
    - .:/app
    command: ["npm", "run", "serve"]
